ChatChatBundle:
    resource: "@ChatChatBundle/Resources/config/routing.yml"
    prefix:   /chat

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
